In [1]:
print("I am a learner and i am here today to learn")

I am a learner and i am here today to learn


In [2]:
str = 'My Name is Vikrant'

In [3]:
print(str[0])

M


In [4]:
print(str[:])

My Name is Vikrant


In [5]:
a = b = c = 1
print(a,b,c)

1 1 1


In [6]:
print(id(a))

2091606436144


In [7]:
print(id(a),id(b),id(c))
# use id() to get the object location in python
# alicing concepts in pythom

2091606436144 2091606436144 2091606436144


In [8]:
str = 'Vikrant and Vijay was going to home.'
print(str)

Vikrant and Vijay was going to home.


In [9]:
print(str[:1])
print(str[::1])
print(str[5])
print(str[-12])


V
Vikrant and Vijay was going to home.
n
i


In [10]:
print(str[1:8])
print(str[1:9])
print(str[1:])
print(str[:10])
print(str[:-1])
print(str[-1:])
print(str[::-1])
print(str[-1::])
print(str[8])
print(str[7])

ikrant 
ikrant a
ikrant and Vijay was going to home.
Vikrant an
Vikrant and Vijay was going to home
.
.emoh ot gniog saw yajiV dna tnarkiV
.
a
 


In [11]:
print(str[-36:])
# to print whole string with the help of  negative indexing

Vikrant and Vijay was going to home.


In [12]:
#    "str[0] = a" this code will not run

# not possible
# updation of a string's character can't be done 


In [13]:
str ="Vikrant"
print(str)

Vikrant


In [14]:
#default order
string1 = '{} {} {}'.format('vikrant','python','java')
print(string1)

vikrant python java


In [15]:
#positional formatting
# will vary the position with resoect to index
string1 = '{1} {2} {0}'.format('vikrant','python','java')
print("\nthis is positional formatting")
print(string1)


this is positional formatting
python java vikrant


In [16]:
string1 = '{2} {0} {1}'.format('vikrant','python','java')
print(string1)

java vikrant python


In [17]:
#keyword formatting
#based on keyword
string1 = '{a} {d} {b} {c}'.format(a = 'vikrant',b = 'python',c = 'java',d = 'javascript')
print(string1)

vikrant javascript python java


In [18]:
string1 = '{d} {c} {a} {b}'.format(a = 'vikrant',b = 'python',c = 'java',d = 'javascript')
print(string1)

javascript java vikrant python


In [19]:
list = [1,2,3,4,5,6,7,8,9,10]
vikrant = ['Vijay', 34 ,56, 45]

#to print the list
print(list)

#to print two list together (concatenated lists)
print(list + vikrant)

#to print two times a list
print(list * 2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'Vijay', 34, 56, 45]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [20]:
#access list element through elements
print(list[2])
print(vikrant[0])


# updation of a list
list[0] = 45
print(list)

3
Vijay
[45, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [21]:
# taking input from user

In [22]:
n = input('User is allowed to Enter anything')
print(n)

User is allowed to Enter anything



In [23]:
# taking input from user in list

In [24]:
list3 = list(map(int,input().split()))
print(list3)

TypeError: 'list' object is not callable

In [ ]:
str = input("Enter any sequence")


In [ ]:
print(str.split("s"))


In [ ]:
str = input("Enter any sequence")
print(str.split("22"))

In [25]:
# nested list
n_list = ['Vikrant',[2,0,1,5] ]
print(n_list[0][1])
 print(n_list[1][2])

IndentationError: unexpected indent (3371688066.py, line 4)

In [26]:
tuple = ('vikrant',12,34,45.0)
print(tuple)
vijay = ('japnaam','nitish',12.0,23,25)
print(vijay * 2)
print(vijay + tuple)

('vikrant', 12, 34, 45.0)
('japnaam', 'nitish', 12.0, 23, 25, 'japnaam', 'nitish', 12.0, 23, 25)
('japnaam', 'nitish', 12.0, 23, 25, 'vikrant', 12, 34, 45.0)


In [27]:
print(tuple[2])
print(tuple[2:])

34
(34, 45.0)


In [28]:
# DICTIONARY IN PYTHON

In [29]:
dict1 = {}
dict1['one'] = "this is python"
dict1['two'] = "this is java"

In [30]:
print(dict1['one'])
print(dict1['two'])

this is python
this is java


In [31]:
dict2 = {'name':'vikrant','id':200305124082,'class':'ai_b2'}
print(dict2.keys())
print(dict2.values())

dict_keys(['name', 'id', 'class'])
dict_values(['vikrant', 200305124082, 'ai_b2'])


In [32]:
#WAP TO FIND OUT FACTORIAL OF A GIVEN NUMBER

In [33]:
number = int(input("Enter a Number"))
factorial = 1
if number<0:
    print("factorial DNE")
elif number==0:
    print("the factorial of 0 is 1")
else:
    for i in range(1,number + 1):
        factorial = factorial*i
print("The factorial of", number,"is",factorial)

Enter a Number


ValueError: invalid literal for int() with base 10: ''

In [34]:
#WAP TO FIND THE SUM OF A DIGIT

In [35]:
def getSum(n):
    
    sum = 0
    while (n != 0):
        
        sum = sum + (n % 10)
        n = n//10
        
    return sum

n = int(input("Enter the number"))
print(getSum(n))

Enter the number


ValueError: invalid literal for int() with base 10: ''

In [36]:
#WAP TO REVERSE A NUMBER 

In [37]:
# WAP TO CHECK RATHER A GIVEN NUMBER IS PALINDROME OR NOT?

In [38]:
n=int(input("Enter number:"))
temp=n
reverse=0
while(n>0):
    dig=n%10
    reverse=reverse*10+dig
    n=n//10
if(temp==reverse):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")

Enter number:


ValueError: invalid literal for int() with base 10: ''

In [39]:
"""
4. PERFORM A CASE STUDY AND PERFORM THE FOLLOWING OPERATIONS ON TUPLES.
  A. MAXIMA.
  B. MINIMA.
  C. SUM OF TWO TUPLES.
  D. DUPLICATE OF A TUPLE.
  E. SLICING OPERATIONS.
  F. OBTAINING A LIST FROM TUPLE.
  G. COMPARING TWO TUPLES.
  H. PRINTING TWO TUPLES OF DIFFERENT DATATYOES.
  
"""

vikrant = (234, 12, 45, 56, 4556)
result = max(vikrant)
print('maximum :', result)




maximum : 4556


In [40]:
"""
4. PERFORM A CASE STUDY AND PERFORM THE FOLLOWING OPERATIONS ON TUPLES.
  A. MAXIMA.
  B. MINIMA.
  C. SUM OF TWO TUPLES.
  D. DUPLICATE OF A TUPLE.
  E. SLICING OPERATIONS.
  F. OBTAINING A LIST FROM TUPLE.
  G. COMPARING TWO TUPLES.
  H. PRINTING TWO TUPLES OF DIFFERENT DATATYOES.
  
"""
t = (1,5,7,8)
maxval = max(t);
print(maxval)
# for i in t:
#     if(i>maxval):
#         maxval = i;
# print(i)

#b> Minimum value:
print(min(t))
# minval = 0;
# for i in range(0, len(t)-1):
#     for j in range(i+1, len(t)):
#         if(t[i]>t[j]):
#             temp = t[i]
#             t[i] = t[j]
#             t[j] = temp
# print(t[0])

#c> sum of two tuples:
t1 = (5, 4, 9)
t2 = (10, 8, 7)

s1 = sum(t1);
s2 = sum(t2);

print(s1+s2);
    


#d> Duplicate tuples:

t1 = (1,2,6,5,8,7,9,2,1,2,4)
a = []
for i in t1:
    n = t1.count(i)
    if n>1:
        if a.count(i) == 0:
            a.append(i)
print(a)

#e> slicing operations:
print(t1[1:5])
print(t1[0:5])
print(t1[5:])
print(t1[:])

#f> obtaining the list from the tuple:
l = [1,5,6,7]
t = (1,5,6,7,l, 8,9,8)
if(l in t):
    print("List fount in Tuple = ",l)
else:
    print(False)


#g> Comparing two tuples:
t1 = (1,5,6,9,8)
t2 = (1,6,8,9,3)
if(t1 == t2):
    print(True)
else:
    print(False)

#h> Printing two tuples of different datatypes:

t1 = ("Vijay", "Ram", "Sham")
t2 = (5, 8, 3)
print("Tuple_1: ",t1)
print("Tuple_2:", t2)



8
1
43
[1, 2]
(2, 6, 5, 8)
(1, 2, 6, 5, 8)
(7, 9, 2, 1, 2, 4)
(1, 2, 6, 5, 8, 7, 9, 2, 1, 2, 4)
List fount in Tuple =  [1, 5, 6, 7]
False
Tuple_1:  ('Vijay', 'Ram', 'Sham')
Tuple_2: (5, 8, 3)


In [3]:
import numpy as np
x = np.ones((3,4))
y = np.zeros((3,4))
print(x*y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
import numpy as np
np.mean([1,2,3,4,5])


3.0

In [8]:
#random generator number
#importance of random seed
import numpy as np
np.ptp([1,5,3])

4