In [1]:
import numpy as np

In [7]:
#to create an 
arr = np.array([[1,2,3,4,5,6,],[3,5,6,7,7,9],[3,5,6,7,8,9]])
arr

array([[1, 2, 3, 4, 5, 6],
       [3, 5, 6, 7, 7, 9],
       [3, 5, 6, 7, 8, 9]])

In [10]:
#to print dimension
print(arr.ndim)

2


In [11]:
#to print the rows and columns
print(arr.shape)

(3, 6)


In [12]:
#get the memory location
print(arr.data)

In [13]:
#print datatype
print(arr.dtype)

int32


In [14]:
print(arr[0,1])

2


# IN 2D ARRAY

In [15]:
v = np.array([[3,4,5],[4,5,6],[6,7,8]])
print(v,"\n")

[[3 4 5]
 [4 5 6]
 [6 7 8]] 



In [16]:
v.dtype

dtype('int32')

In [17]:
v.itemsize

4

In [18]:
#to get elements
v.size

9

In [20]:
v = np.array([[3,4,5],[4,5,6],[6,7,8]], dtype=np.float64)
print(v,"\n")
print(v.dtype,"\n")
print(v.size)

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

float64 

9


In [23]:
x= np.array([[3,4,5],[4,5,6],[6,7,8]], dtype=np.complex64)
y= np.array([[3,4,5],[4,5,6],[6,7,8]], dtype=np.complex128)

print(x,"\n")
print(x.dtype,"\n")
print(x.itemsize,"\n")
print(y,"\n")
print(y.dtype,"\n")
print(y.itemsize)

[[3.+0.j 4.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [6.+0.j 7.+0.j 8.+0.j]] 

complex64 

8 

[[3.+0.j 4.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [6.+0.j 7.+0.j 8.+0.j]] 

complex128 

16


In [30]:
print((v))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]]


In [32]:
print(np.sum(v))

48.0


In [37]:
#sum value along a specific axis
# axis 0 = columnwise
# axis 1 = rowwise
print(v,"\n")
print(np.sum(v, axis = 0))
print(np.sum(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

[13. 16. 19.]
[12. 15. 21.]


# minimum value

In [38]:
print(v,"\n")
print(np.amin(v))
print(np.amin(v, axis = 0))
print(np.amin(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

3.0
[3. 4. 5.]
[3. 4. 6.]


# MAXIMUM VALUE

In [43]:
print(v,"\n")
print(np.amax(v))
print(np.amax(v, axis = 0))
print(np.amax(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

8.0
[6. 7. 8.]
[5. 6. 8.]


# MEAN

In [40]:
print(v,"\n")
print(np.mean(v))
print(np.mean(v, axis = 0))
print(np.mean(v, axis = 1))
print(type(v))


[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

5.333333333333333
[4.33333333 5.33333333 6.33333333]
[4. 5. 7.]
<class 'numpy.ndarray'>


# STANDARD DEVIATION

In [41]:
print(v,"\n")
print(np.std(v))
print(np.std(v, axis = 0))
print(np.std(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

1.4907119849998598
[1.24721913 1.24721913 1.24721913]
[0.81649658 0.81649658 0.81649658]


# MEDIAN

In [42]:
print(v,"\n")
print(np.median(v))
print(np.median(v, axis = 0))
print(np.median(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

5.0
[4. 5. 6.]
[4. 5. 7.]


# VARIANCE

In [45]:
print(v,"\n")
print(np.var(v))
print(np.var(v, axis = 0))
print(np.var(v, axis = 1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

2.2222222222222223
[1.55555556 1.55555556 1.55555556]
[0.66666667 0.66666667 0.66666667]


In [46]:
#WEIGHTED AVERAGWE
print(np.average(v))

5.333333333333333


In [49]:
c = np.array([2,5,6,3,4,5,6,7,8,7,8,10])
print(c)

[ 2  5  6  3  4  5  6  7  8  7  8 10]


In [53]:
weight = np.array([24,45,34,24,34,24,44,67,778,78,98,45])
print(weight)

[ 24  45  34  24  34  24  44  67 778  78  98  45]


In [54]:
print(np.average(c, weights=weight))

7.3683397683397684


# PERCENTILE

In [59]:
print(c,"\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(v,5,1))

[ 2  5  6  3  4  5  6  7  8  7  8 10] 

2.55
2.88
[3.1 4.1 6.1]


# PEAK TO PEAK

In [63]:
print(v,"\n")
print(c,"\n")

print(np.ptp(c,0))
print(np.ptp(v,0))
print(np.ptp(v,1))

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

[ 2  5  6  3  4  5  6  7  8  7  8 10] 

8
[3. 3. 3.]
[2. 2. 2.]


In [65]:
print(v,"\n")
print(v.shape,"\n")
print(v.reshape(1,9),"\n")
print(v)

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]] 

(3, 3) 

[[3. 4. 5. 4. 5. 6. 6. 7. 8.]] 

[[3. 4. 5.]
 [4. 5. 6.]
 [6. 7. 8.]]


# SLICING

In [71]:
l= np.array([[24,45,27,29],[34,56,67,34],[34,87,98,23]])
print(l,"\n")
#to print element based on matrix location
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")

#to print from zeroth row  and first column
print(l[0:2,1],"\n")

print(l[0,0:3],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")
print(l[0:2,1:3],"\n")

[[24 45 27 29]
 [34 56 67 34]
 [34 87 98 23]] 

29 

67 

23 

[45 56] 

[24 45 27] 

[34 87 98 23] 

[34 87] 

[[45 27]
 [56 67]] 



# STACKING

In [74]:
s=np.arange(12).reshape(3,4)
print(s,"\n")
t= np.arange(35,47).reshape(3,4)
print(t)                           

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [76]:
print(s,"\n")
print(t,"\n")
print(np.hstack((s,t)),"\n")
print(np.hstack((t,s)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]] 

[[ 0  1  2  3 35 36 37 38]
 [ 4  5  6  7 39 40 41 42]
 [ 8  9 10 11 43 44 45 46]] 

[[35 36 37 38  0  1  2  3]
 [39 40 41 42  4  5  6  7]
 [43 44 45 46  8  9 10 11]] 



In [77]:
print(s,"\n")
print(t,"\n")
print(np.vstack((s,t)),"\n")
print(np.vstack((t,s)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]] 

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



# RANDOM NUMBER GENERATOR

In [79]:
from numpy import random

In [80]:
#to int
x= random.randint(100)
print(x)

18


In [84]:
# to float
y = random.rand()
print(y)

0.2751456687413262
